todo/core/urls.py
from django.urls.conf import path
from todo.core import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:task_id>', views.detail, name='detail'),
    path('delete/<int:task_id>', views.delete, name='delete')
]

todo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from todo.home_view import home

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('tasks/', include('todo.core.urls'))
]

todo/core/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length = 128, help_text="title")
    done = models.BooleanField(default = False)

todo/core/forms.py
from django.forms.models import ModelForm
from todo.core.models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'done']

todo/core/views.py
from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from todo.core.models import Task
from todo.core.forms import TaskForm

# Create your views here.
def home(request):
    pending_tasks = Task.objects.filter(done=False)
    completed_tasks = Task.objects.filter(done=True)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:home'))
        return render(
            request, 'tasks/home.html', 
            {
                'form': form, 
                'pending_tasks': pending_tasks,
                'completed_tasks': completed_tasks
            },
            status=400
        )
    return render(
        request, 'tasks/home.html', 
        {
            'pending_tasks': pending_tasks,
            'completed_tasks': completed_tasks
        })

def detail(request, task_id):
    task = Task.objects.get(id=task_id)
    form = TaskForm(request.POST, instance=task)
    if form.is_valid():
        form.save()
    return HttpResponseRedirect(reverse('core:home'))

def delete(request, task_id):
    if request.method == 'POST':
        Task.objects.filter(id=task_id).delete()
    return HttpResponseRedirect(reverse('core:home'))

todo/core/templates/tasks/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tarefas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1 class="mt-5">Lista de Tarefas</h1>

                <form action="{% url 'core:home' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Descreva sua tarefa"
                            aria-label="Descreva sua tarefa" aria-describedby="btn-add" name="title">
                        <button type="submit" class="btn btn-primary" id="btn-add">Adicionar</button>
                    </div>
                    <small class="form-text text-muted">{{ form.title.errors }}</small>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="mt-5">Tarefas Pendentes</h2>
                {% for task in pending_tasks %}
                    <form action="{% url 'core:detail' task_id=task.id %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Descreva sua tarefa" required="required"
                                aria-label="Descreva sua tarefa" aria-describedby="btn-add" name="title" value="{{ task.title }}">
                            <input type="hidden" value="checked" name="done">
                            <button type="submit" class="btn btn-success" id="btn-add">Marcar como feita</button>
                        </div>
                    </form>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="mt-5">Tarefas concluídas</h2>
                {% for task in completed_tasks %}
                    <div class="row">
                        <div class="col-2">
                        <form action="{% url 'core:delete' task_id=task.id %}" method="POST">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <button type="submit" class="btn btn-danger" id="btn-add">Deletar</button>
                            </div>
                        </form>
                        </div>
                        <div class="col-10">
                        <form action="{% url 'core:detail' task_id=task.id %}" method="POST">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Descreva sua tarefa" required="required"
                                    aria-label="Descreva sua tarefa" aria-describedby="btn-add" name="title" value="{{ task.title }}">
                                <button type="submit" class="btn btn-warning" id="btn-add">Marcar como pendente</button>
                            </div>
                        </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>

</html>